import System.utils.Collections

any function main() {
    print("=== Running All DSA Tests ===\n")
    
    // HashMap Tests
    print("--- HashMap ---")
    let map = Collections.HashMap.create()
    Collections.HashMap.set(map, "key1", "value1")
    Collections.HashMap.set(map, "key2", 42)
    print("Created map with 2 entries")
    print("Size:", Collections.HashMap.size(map))
    print("Get key1:", Collections.HashMap.get(map, "key1"))
    print("Has key2:", Collections.HashMap.has(map, "key2"))
    print("Keys:", Collections.HashMap.keys(map))
    print("Values:", Collections.HashMap.values(map))
    print("Entries:", Collections.HashMap.entries(map))
    Collections.HashMap.remove(map, "key1")
    print("Size after remove:", Collections.HashMap.size(map))
    Collections.HashMap.clear(map)
    print("Size after clear:", Collections.HashMap.size(map))
    
    // LinkedList Tests
    print("\n--- LinkedList ---")
    let list = Collections.LinkedList.create()
    Collections.LinkedList.add(list, "first")
    Collections.LinkedList.add(list, "second")
    Collections.LinkedList.add(list, "third")
    print("Created list with 3 elements")
    print("Size:", Collections.LinkedList.size(list))
    print("Get index 0:", Collections.LinkedList.get(list, 0))
    print("Get first:", Collections.LinkedList.getFirst(list))
    print("Get last:", Collections.LinkedList.getLast(list))
    Collections.LinkedList.addFirst(list, "zero")
    print("After addFirst:", Collections.LinkedList.getFirst(list))
    Collections.LinkedList.remove(list, "second")
    print("Size after remove:", Collections.LinkedList.size(list))
    print("To array:", Collections.LinkedList.toArray(list))
    
    // Stack Tests
    print("\n--- Stack ---")
    let stack = Collections.Stack.create()
    Collections.Stack.push(stack, "a")
    Collections.Stack.push(stack, "b")
    Collections.Stack.push(stack, "c")
    print("Pushed a, b, c")
    print("Size:", Collections.Stack.size(stack))
    print("Peek:", Collections.Stack.peek(stack))
    print("Pop:", Collections.Stack.pop(stack))
    print("Peek after pop:", Collections.Stack.peek(stack))
    print("To array:", Collections.Stack.toArray(stack))
    
    // Queue Tests
    print("\n--- Queue ---")
    let queue = Collections.Queue.create()
    Collections.Queue.enqueue(queue, "x")
    Collections.Queue.enqueue(queue, "y")
    Collections.Queue.enqueue(queue, "z")
    print("Enqueued x, y, z")
    print("Size:", Collections.Queue.size(queue))
    print("Peek:", Collections.Queue.peek(queue))
    print("Dequeue:", Collections.Queue.dequeue(queue))
    print("Peek after dequeue:", Collections.Queue.peek(queue))
    print("To array:", Collections.Queue.toArray(queue))
    
    // PriorityQueue Tests
    print("\n--- PriorityQueue ---")
    let pq = Collections.PriorityQueue.create()
    Collections.PriorityQueue.enqueue(pq, 5)
    Collections.PriorityQueue.enqueue(pq, 2)
    Collections.PriorityQueue.enqueue(pq, 8)
    print("Enqueued 5, 2, 8")
    print("Size:", Collections.PriorityQueue.size(pq))
    print("Peek (should be 2):", Collections.PriorityQueue.peek(pq))
    print("Dequeue:", Collections.PriorityQueue.dequeue(pq))
    print("Next peek:", Collections.PriorityQueue.peek(pq))
    
    // Trie Tests
    print("\n--- Trie ---")
    let trie = Collections.Trie.create()
    Collections.Trie.insert(trie, "hello")
    Collections.Trie.insert(trie, "world")
    Collections.Trie.insert(trie, "hey")
    print("Inserted: hello, world, hey")
    print("Search 'hello':", Collections.Trie.search(trie, "hello"))
    print("Search 'hey':", Collections.Trie.search(trie, "hey"))
    print("Starts with 'he':", Collections.Trie.startsWith(trie, "he"))
    print("All words:", Collections.Trie.getAllWords(trie))
    print("Size:", Collections.Trie.size(trie))
    Collections.Trie.remove(trie, "hey")
    print("Size after remove 'hey':", Collections.Trie.size(trie))
    
    print("\n=== All DSA tests completed ===")
}
