import System.utils.Math

print("pi:", Math.pi)
print("e:", Math.e)
print("sin(0):", Math.sin(0))
print("cos(0):", Math.cos(0))
print("tan(0):", Math.tan(0))
print("sqrt(16):", Math.sqrt(16))
print("pow(2, 10):", Math.pow(2, 10))
print("floor(3.7):", Math.floor(3.7))
print("ceil(3.2):", Math.ceil(3.2))
print("round(3.5):", Math.round(3.5))
print("abs(-5):", Math.abs(-5))
print("min(1, 2, 3):", Math.min(1, 2, 3))
print("max(1, 2, 3):", Math.max(1, 2, 3))
print("random():", Math.random())
print("factorial(5):", Math.factorial(5))
print("gcd(48, 18):", Math.gcd(48, 18))
print("lcm(4, 6):", Math.lcm(4, 6))